### register user
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Muhammad Bashir Ibrahim",
    "email": "mbashirhibrahim7@gmail.com",
    "password": "muhdbashir"
}


### user login
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "mbashiribrahim7@gmail.com",
    "password": "muhdbashir"
}

### get all users
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQzNTgzMDQ2fQ.HDBGdK-760kQPQtJfvzn8bS-Ez2sGQeVRiOiKB9BzaQ


### get single user
GET http://localhost:5000/api/v1/users/1

### update user
PUT  http://localhost:5000/api/v1/users/1
Content-Type: application/json

{
    "name": "muhd bashir"
}

### delete user
DELETE http://localhost:5000/api/v1/users/1

### create booking
POST  http://localhost:5000/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNjUxMDg1fQ.RYJcJ6UFBnbiQVI_UVvKtSn2yymvg3z8uDAo9le1YR4

{

  "workspaceId": 1,
  "startTime": "2025-07-25T14:00:00",
  "endTime": "2025-07-25T16:00:00",
  "attendees": 4,
  "specialRequests": "Need a projector"
}


###
 GET http://localhost:5000/api/v1/bookings/availability/1?startTime=2025-07-25T14:00:00Z&endTime=2025-07-25T16:00:00Z&attendees=6



###
 GET http://localhost:5000/api/v1/bookings/


###
GET http://localhost:5000/api/v1/bookings/user?upcoming=true&page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNjY4NTcyfQ.tMWQlQbUEgjNPNhV9D0IcggTfD5GInByKcIt9zR_saM