### register user
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Muhammad Bashir Ibrahim",
    "email": "zaccodder@gmail.com",
    "password": "zaccodder"
}


### user login
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "zaccodder@gmail.com",
    "password": "zaccodder"
}

### get all users
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzQzNjkzMzYzfQ.qvSSnTbKPr8pjJzbzMLC1lUOArd7iVNfGng2gNX4SH8


### get single user
GET http://localhost:5000/api/v1/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzQzNjkzMzYzfQ.qvSSnTbKPr8pjJzbzMLC1lUOArd7iVNfGng2gNX4SH8

### update user
PUT  http://localhost:5000/api/v1/users/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzQzNjkzMzYzfQ.qvSSnTbKPr8pjJzbzMLC1lUOArd7iVNfGng2gNX4SH8

{
    "name": "muhd bashir"
}

### delete user
DELETE http://localhost:5000/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzQzNjkzMzYzfQ.qvSSnTbKPr8pjJzbzMLC1lUOArd7iVNfGng2gNX4SH8

### create booking
POST  http://localhost:5000/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzQzNzU5OTY3fQ.yn_gwKhib-WnUTIK3CKnxcqBOMsJp0kPWenCTOt3Ly0

{

  "workspaceId": 1,
  "startTime": "2025-08-25T14:00:00",
  "endTime": "2025-08-25T16:00:00",
  "attendees": 4,
  "specialRequests": "Need a projector"
}


###
 GET http://localhost:5000/api/v1/bookings/availability/3?startTime=2025-07-25T14:00:00Z&endTime=2025-07-25T16:00:00Z&attendees=6

###
 GET http://localhost:5000/api/v1/bookings/

###
GET http://localhost:5000/api/v1/bookings/user?upcoming=true&page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzQzNjkzMzYzfQ.qvSSnTbKPr8pjJzbzMLC1lUOArd7iVNfGng2gNX4SH8